Dockerize
hannahcode/wordle pull request #29
Opened 2022-01-17 18:44 UTC by tcuc

add dockerfile
add docker build instructions

2022-01-18 01:15 UTC, hannahcode requested changes

2022-01-18 01:15 UTC, hannahcode commented on README.md
> +open http://localhost:3000 in browser.
It appears this is using your file directory structure, can we make this generic?

2022-01-18 11:33 UTC, tcuc commented on README.md
> +open http://localhost:3000 in browser.
I wrote it relative to the repo root dir.
And i made the assumption that it is running locally.
So I'm not quite sure what else could be done more generic?
I also admit that i may be overlooking something obvious, so please let me know if I'm overlooking something. :slightly_smiling_face:

2022-01-18 14:48 UTC, Bockiii commented on README.md
> +open http://localhost:3000 in browser.
when this is merged, I'll open a PR to do github autobuilds and host the container in the ghcr. Then nobody should really need to locally build it.

2022-01-18 15:35 UTC, tcuc commented on README.md
> +open http://localhost:3000 in browser.
Sweet!

2022-01-18 19:29 UTC, hannahcode commented on README.md
> +open http://localhost:3000 in browser.
Got it - lets remove the "cd wordle" line, because we can assume the user is already in the directory?

2022-01-18 19:36 UTC, Bockiii commented on README.md
> +open http://localhost:3000 in browser.
sure

2022-01-19 04:52 UTC, tcuc commented on README.md
> +open http://localhost:3000 in browser.
I agree :)

2022-01-19 16:20 UTC, merged